import React from 'react';
import { 
    CAMPAIGN_SUMMARY, REPORT_DATA, OVERVIEW_EXPOSURE, ASSETS, 
    POI_RELEVANCE, UPLIFT_DATA, CREATIVE_INSIGHTS 
} from '../data/mockData';
import { 
    Download, Printer, TrendingUp, Users, Target, Zap, 
    Calendar, MapPin, Layers, ArrowRight, Activity, ShieldCheck 
} from 'lucide-react';
import { 
    AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, 
    BarChart, Bar, Cell, PieChart, Pie, Legend 
} from 'recharts';

const Report: React.FC = () => {
  return (
    <div className="p-4 md:p-8 bg-neutral-100 min-h-screen font-sans">
        {/* Toolbar */}
        <div className="max-w-5xl mx-auto mb-6 flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
            <div>
                <h1 className="text-2xl md:text-3xl font-bold text-black font-heading tracking-tight">Campaign Analysis Report</h1>
                <p className="text-sm text-neutral-500">Ready for export and stakeholder presentation.</p>
            </div>
            <div className="flex gap-3 w-full md:w-auto">
                 <button className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2 bg-white border border-neutral-300 hover:bg-neutral-50 font-bold text-xs uppercase tracking-wider text-black transition-colors rounded-sm shadow-sm">
                    <Printer size={16} />
                    Print
                </button>
                <button className="flex-1 md:flex-none flex items-center justify-center gap-2 px-4 py-2 bg-black text-white hover:bg-neutral-800 font-bold text-xs uppercase tracking-wider transition-colors rounded-sm shadow-sm">
                    <Download size={16} />
                    Export PDF
                </button>
            </div>
        </div>

        {/* REPORT DOCUMENT CONTAINER */}
        <div className="max-w-5xl mx-auto bg-white shadow-xl border border-neutral-200 min-h-[1200px] print:shadow-none print:border-none">
            
            {/* 1. HEADER SECTION */}
            <div className="bg-black text-white p-6 md:p-10 relative overflow-hidden">
                <div className="relative z-10 flex flex-col md:flex-row justify-between items-start gap-6">
                    <div>
                        <div className="flex items-center gap-2 mb-2">
                             <span className="bg-green-500 text-black text-[10px] font-extrabold px-2 py-0.5 rounded uppercase tracking-wider">Completed Analysis</span>
                        </div>
                        <h1 className="text-3xl md:text-4xl font-bold tracking-tight mb-2 font-heading">{CAMPAIGN_SUMMARY.name}</h1>
                        <p className="text-neutral-400 font-medium">Post-Campaign Intelligence Report</p>
                    </div>
                    <div className="text-left md:text-right w-full md:w-auto">
                        <div className="flex items-center md:justify-end gap-2 text-neutral-400 mb-1">
                            <Calendar size={14} />
                            <span className="text-sm font-mono">{CAMPAIGN_SUMMARY.startDate} — {CAMPAIGN_SUMMARY.endDate}</span>
                        </div>
                        <p className="text-xs text-neutral-500 uppercase tracking-widest font-bold">Generated by Adnoxy</p>
                    </div>
                </div>
                {/* Background Pattern */}
                <div className="absolute right-[-50px] top-[-50px] opacity-10 pointer-events-none">
                    <Activity size={300} />
                </div>
            </div>

            {/* 2. KEY METRICS STRIP */}
            <div className="grid grid-cols-2 md:grid-cols-4 border-b border-neutral-200 bg-neutral-50 divide-x divide-y md:divide-y-0 divide-neutral-200">
                <div className="p-4 md:p-6">
                    <p className="text-[10px] font-bold text-neutral-500 uppercase tracking-widest mb-2 font-heading">Total Impressions</p>
                    <p className="text-2xl md:text-3xl font-bold text-black font-heading">{(REPORT_DATA.summary.totalImpressions / 1000000).toFixed(1)}M</p>
                    <p className="text-xs text-green-600 font-bold mt-1 flex items-center gap-1"><TrendingUp size={12}/> +4.2% vs target</p>
                </div>
                <div className="p-4 md:p-6">
                    <p className="text-[10px] font-bold text-neutral-500 uppercase tracking-widest mb-2 font-heading">Unique Reach</p>
                    <p className="text-2xl md:text-3xl font-bold text-black font-heading">{(REPORT_DATA.summary.audienceReached / 1000000).toFixed(1)}M</p>
                    <p className="text-xs text-neutral-500 font-bold mt-1">High Density</p>
                </div>
                <div className="p-4 md:p-6">
                    <p className="text-[10px] font-bold text-neutral-500 uppercase tracking-widest mb-2 font-heading">ROAS Uplift</p>
                    <p className="text-2xl md:text-3xl font-bold text-black font-heading">+{UPLIFT_DATA.monetary.roasUplift}%</p>
                    <p className="text-xs text-green-600 font-bold mt-1">Efficiency Gain</p>
                </div>
                <div className="p-4 md:p-6">
                    <p className="text-[10px] font-bold text-neutral-500 uppercase tracking-widest mb-2 font-heading">Asset Efficiency</p>
                    <div className="flex items-center gap-2">
                        <span className="text-2xl md:text-3xl font-bold text-black font-heading">High</span>
                        <ShieldCheck className="text-green-600" size={24} />
                    </div>
                </div>
            </div>

            {/* MAIN CONTENT AREA */}
            <div className="p-6 md:p-10 space-y-12">

                {/* 3. EXECUTIVE SUMMARY */}
                <section>
                    <div className="flex items-center gap-2 mb-4 border-b border-black pb-2">
                        <span className="bg-black text-white w-6 h-6 flex items-center justify-center font-bold text-xs rounded-full">1</span>
                        <h2 className="text-lg font-bold text-black uppercase tracking-wide font-heading">Executive Summary</h2>
                    </div>
                    <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
                        <div className="lg:col-span-2">
                            <p className="text-neutral-800 leading-relaxed text-sm mb-4">
                                The <strong>{CAMPAIGN_SUMMARY.name}</strong> has delivered strong early performance across visibility, contextual fit, cluster alignment, and retail proximity. The campaign has generated <span className="font-bold">{ (REPORT_DATA.summary.totalImpressions / 1000000).toFixed(1) } million impressions</span>, reaching { (REPORT_DATA.summary.audienceReached / 1000000).toFixed(1) } million unique individuals within {CAMPAIGN_SUMMARY.daysRunning} days.
                            </p>
                            <p className="text-neutral-800 leading-relaxed text-sm">
                                Asset <span className="font-mono bg-neutral-100 px-1 border border-neutral-200 text-xs font-bold">{REPORT_DATA.summary.topAsset}</span> was the top performer due to strong visibility and dominant placement in fitness-heavy corridors, driving a significant portion of the incremental lift observed in Week 2.
                            </p>
                        </div>
                        <div className="bg-indigo-50 border border-indigo-100 p-5 rounded-sm">
                            <div className="flex items-center gap-2 mb-2 text-indigo-900 font-bold text-xs uppercase tracking-wider font-heading">
                                <Zap size={14} fill="currentColor" /> AI Insight
                            </div>
                            <p className="text-indigo-900 text-sm leading-relaxed italic">
                                "Peak exposure clusters appeared consistently around commute-heavy nodes, indicating strong synergy between audience movement patterns and asset placement. Recommendation to increase frequency in these zones."
                            </p>
                        </div>
                    </div>
                </section>

                {/* 4. PERFORMANCE METRICS */}
                <section>
                     <div className="flex items-center gap-2 mb-6 border-b border-black pb-2">
                        <span className="bg-black text-white w-6 h-6 flex items-center justify-center font-bold text-xs rounded-full">2</span>
                        <h2 className="text-lg font-bold text-black uppercase tracking-wide font-heading">Performance Metrics</h2>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
                        {/* 4.1 Daily Exposure Chart */}
                        <div className="bg-white border border-neutral-200 p-4 shadow-sm">
                            <h3 className="text-xs font-bold text-neutral-500 uppercase tracking-widest mb-4 font-heading">Daily Exposure Trend</h3>
                            <div className="h-48">
                                <ResponsiveContainer width="100%" height="100%">
                                    <AreaChart data={OVERVIEW_EXPOSURE}>
                                        <defs>
                                            <linearGradient id="colorReport" x1="0" y1="0" x2="0" y2="1">
                                                <stop offset="5%" stopColor="#000" stopOpacity={0.1}/>
                                                <stop offset="95%" stopColor="#000" stopOpacity={0}/>
                                            </linearGradient>
                                        </defs>
                                        <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#f5f5f5" />
                                        <XAxis dataKey="date" tick={{fontSize: 10}} axisLine={false} tickLine={false} dy={10}/>
                                        <YAxis tick={{fontSize: 10}} axisLine={false} tickLine={false} tickFormatter={(val)=>`${val/1000}k`}/>
                                        <Tooltip contentStyle={{fontSize: '11px'}} />
                                        <Area type="monotone" dataKey="actual" stroke="#000" fill="url(#colorReport)" strokeWidth={2} />
                                        <Area type="monotone" dataKey="baseline" stroke="#a3a3a3" fill="transparent" strokeDasharray="4 4" strokeWidth={2} />
                                    </AreaChart>
                                </ResponsiveContainer>
                            </div>
                        </div>

                        {/* 4.2 Creative Impact Stats */}
                        <div className="bg-white border border-neutral-200 p-4 shadow-sm">
                            <h3 className="text-xs font-bold text-neutral-500 uppercase tracking-widest mb-4 font-heading">Creative Impact Analysis</h3>
                            <div className="space-y-4">
                                <div>
                                    <div className="flex justify-between text-xs mb-1 font-bold">
                                        <span>Legibility Score</span>
                                        <span>{CREATIVE_INSIGHTS.scores.readability * 100}%</span>
                                    </div>
                                    <div className="w-full bg-neutral-100 h-2 rounded-full overflow-hidden">
                                        <div className="bg-green-500 h-full" style={{width: `${CREATIVE_INSIGHTS.scores.readability * 100}%`}}></div>
                                    </div>
                                </div>
                                <div>
                                    <div className="flex justify-between text-xs mb-1 font-bold">
                                        <span>Contrast Ratio</span>
                                        <span>{CREATIVE_INSIGHTS.scores.contrast * 100}%</span>
                                    </div>
                                    <div className="w-full bg-neutral-100 h-2 rounded-full overflow-hidden">
                                        <div className="bg-orange-500 h-full" style={{width: `${CREATIVE_INSIGHTS.scores.contrast * 100}%`}}></div>
                                    </div>
                                </div>
                                <div>
                                    <div className="flex justify-between text-xs mb-1 font-bold">
                                        <span>Obstruction Free</span>
                                        <span>{(1 - CREATIVE_INSIGHTS.scores.obstructionRisk) * 100}%</span>
                                    </div>
                                    <div className="w-full bg-neutral-100 h-2 rounded-full overflow-hidden">
                                        <div className="bg-black h-full" style={{width: `${(1 - CREATIVE_INSIGHTS.scores.obstructionRisk) * 100}%`}}></div>
                                    </div>
                                </div>
                            </div>
                            <div className="mt-4 pt-4 border-t border-neutral-100 flex items-center gap-2 text-xs text-neutral-500">
                                <Activity size={14} /> Creative performed in top 15% of category benchmarks.
                            </div>
                        </div>
                    </div>

                    {/* 4.3 Top Assets Table */}
                    <div className="border border-neutral-200 rounded-sm overflow-x-auto">
                        <table className="w-full text-sm text-left min-w-[500px]">
                            <thead className="bg-neutral-50 text-[10px] font-bold text-neutral-500 uppercase tracking-wider">
                                <tr>
                                    <th className="px-4 py-3">Asset Location</th>
                                    <th className="px-4 py-3">Format</th>
                                    <th className="px-4 py-3 text-right">Daily Imp.</th>
                                    <th className="px-4 py-3 text-right">Visibility</th>
                                    <th className="px-4 py-3 text-right">Context Score</th>
                                </tr>
                            </thead>
                            <tbody className="divide-y divide-neutral-100">
                                {ASSETS.slice(0, 3).map((asset) => (
                                    <tr key={asset.id}>
                                        <td className="px-4 py-3 font-bold text-black">{asset.location}</td>
                                        <td className="px-4 py-3 text-neutral-600 font-mono text-xs">{asset.id}</td>
                                        <td className="px-4 py-3 text-right">{(asset.dailyImpressions/1000).toFixed(1)}k</td>
                                        <td className="px-4 py-3 text-right font-bold text-green-600">{asset.visibilityScore}</td>
                                        <td className="px-4 py-3 text-right">{asset.contextScore}</td>
                                    </tr>
                                ))}
                            </tbody>
                        </table>
                    </div>
                </section>

                {/* 5. AUDIENCE & CONTEXT */}
                <section>
                    <div className="flex items-center gap-2 mb-6 border-b border-black pb-2">
                        <span className="bg-black text-white w-6 h-6 flex items-center justify-center font-bold text-xs rounded-full">3</span>
                        <h2 className="text-lg font-bold text-black uppercase tracking-wide font-heading">Audience & Context Intelligence</h2>
                    </div>
                    
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                        <div>
                             <h3 className="text-xs font-bold text-neutral-500 uppercase tracking-widest mb-4 font-heading">Dominant Personas</h3>
                             <div className="flex flex-wrap gap-3 mb-6">
                                 <span className="px-3 py-1 bg-black text-white text-xs font-bold rounded-full">Youth Active (38%)</span>
                                 <span className="px-3 py-1 bg-neutral-100 text-neutral-800 text-xs font-bold rounded-full">Affluent Lifestyle (27%)</span>
                                 <span className="px-3 py-1 bg-neutral-100 text-neutral-800 text-xs font-bold rounded-full">Weekday Commuter (21%)</span>
                             </div>
                             <div className="bg-neutral-50 p-4 border border-neutral-200">
                                 <h4 className="text-xs font-bold text-black mb-2 flex items-center gap-2 font-heading"><MapPin size={12}/> Catchment Overlap</h4>
                                 <p className="text-xs text-neutral-600 leading-relaxed">
                                     High overlap detected in Downtown corridors during 5-7PM. Audience flow indicates sequential exposure potential of 1.8x frequency.
                                 </p>
                             </div>
                        </div>

                        <div>
                            <h3 className="text-xs font-bold text-neutral-500 uppercase tracking-widest mb-4 font-heading">POI Exposure Categories</h3>
                            <div className="h-40">
                                <ResponsiveContainer width="100%" height="100%">
                                    <BarChart data={POI_RELEVANCE} layout="vertical" margin={{left: 20}}>
                                        <CartesianGrid strokeDasharray="3 3" horizontal={false} stroke="#f5f5f5" />
                                        <XAxis type="number" hide />
                                        <YAxis dataKey="name" type="category" axisLine={false} tickLine={false} tick={{fontSize: 10, fontWeight: 600}} width={60} />
                                        <Bar dataKey="value" barSize={16} radius={[0, 4, 4, 0]}>
                                            {POI_RELEVANCE.map((entry, index) => (
                                                <Cell key={`cell-${index}`} fill={index === 0 ? '#000' : '#a3a3a3'} />
                                            ))}
                                        </Bar>
                                    </BarChart>
                                </ResponsiveContainer>
                            </div>
                        </div>
                    </div>
                </section>

                {/* 6. ATTRIBUTION & ROI */}
                <section>
                    <div className="flex items-center gap-2 mb-6 border-b border-black pb-2">
                        <span className="bg-black text-white w-6 h-6 flex items-center justify-center font-bold text-xs rounded-full">4</span>
                        <h2 className="text-lg font-bold text-black uppercase tracking-wide font-heading">Attribution & ROI Summary</h2>
                    </div>

                    <div className="bg-neutral-50 border border-neutral-200 p-6 rounded-sm mb-6">
                        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center divide-y md:divide-y-0 md:divide-x divide-neutral-200">
                             <div className="pt-4 md:pt-0">
                                 <p className="text-xs font-bold text-neutral-500 uppercase tracking-widest mb-2 font-heading">Incremental Lift</p>
                                 <p className="text-4xl font-bold text-black font-heading">+{UPLIFT_DATA.incrementalLift.value}%</p>
                                 <p className="text-xs text-green-600 font-bold mt-1">Above Baseline</p>
                             </div>
                             <div className="pt-4 md:pt-0">
                                 <p className="text-xs font-bold text-neutral-500 uppercase tracking-widest mb-2 font-heading">Est. Conversions</p>
                                 <p className="text-4xl font-bold text-black font-heading">{UPLIFT_DATA.incrementalLift.estimatedConversions.toLocaleString()}</p>
                                 <p className="text-xs text-neutral-500 font-bold mt-1">+8.4% Attributed to OOH</p>
                             </div>
                             <div className="pt-4 md:pt-0">
                                 <p className="text-xs font-bold text-neutral-500 uppercase tracking-widest mb-2 font-heading">Channel Synergy</p>
                                 <div className="text-left inline-block pl-4">
                                     <p className="text-xs font-medium text-neutral-700 mb-1">+9% Search Lift</p>
                                     <p className="text-xs font-medium text-neutral-700 mb-1">+6% Retail Visits</p>
                                     <p className="text-xs font-medium text-neutral-700">+12% Direct Web</p>
                                 </div>
                             </div>
                        </div>
                    </div>
                </section>

                {/* 7. FORECAST & RECOMMENDATIONS */}
                <section className="break-inside-avoid">
                     <div className="flex items-center gap-2 mb-6 border-b border-black pb-2">
                        <span className="bg-black text-white w-6 h-6 flex items-center justify-center font-bold text-xs rounded-full">5</span>
                        <h2 className="text-lg font-bold text-black uppercase tracking-wide font-heading">Strategic Forecast</h2>
                    </div>

                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
                        <div>
                             <h3 className="text-xs font-bold text-neutral-500 uppercase tracking-widest mb-4 font-heading">Strategic Recommendations</h3>
                             <ul className="space-y-4">
                                <li className="flex gap-3">
                                    <span className="flex-shrink-0 w-5 h-5 bg-black text-white flex items-center justify-center font-bold text-[10px] rounded-full mt-0.5">1</span>
                                    <div>
                                        <p className="text-sm font-bold text-black">Increase focus around fitness clusters</p>
                                        <p className="text-xs text-neutral-600">Drive additional efficiency by rotating more visibility-strong assets into these zones.</p>
                                    </div>
                                </li>
                                <li className="flex gap-3">
                                    <span className="flex-shrink-0 w-5 h-5 bg-black text-white flex items-center justify-center font-bold text-[10px] rounded-full mt-0.5">2</span>
                                    <div>
                                        <p className="text-sm font-bold text-black">Shift creatives toward higher contrast</p>
                                        <p className="text-xs text-neutral-600">Improves readability in high-glare environments encountered in the southern sector.</p>
                                    </div>
                                </li>
                                <li className="flex gap-3">
                                    <span className="flex-shrink-0 w-5 h-5 bg-black text-white flex items-center justify-center font-bold text-[10px] rounded-full mt-0.5">3</span>
                                    <div>
                                        <p className="text-sm font-bold text-black">Activate second-wave assets near malls</p>
                                        <p className="text-xs text-neutral-600">Aligns with rising weekend audience density projected for late January.</p>
                                    </div>
                                </li>
                             </ul>
                        </div>
                        
                        <div className="bg-neutral-900 text-white p-6 rounded-sm">
                            <h3 className="text-xs font-bold text-neutral-400 uppercase tracking-widest mb-4 flex items-center gap-2 font-heading"><Target size={14} /> 30-Day Forecast</h3>
                            <div className="space-y-6">
                                <div>
                                    <p className="text-xs text-neutral-400 mb-1">Projected Reach Growth</p>
                                    <p className="text-3xl font-bold font-heading">5.1M <span className="text-sm font-normal text-neutral-500 font-sans">Individuals</span></p>
                                </div>
                                <div>
                                    <p className="text-xs text-neutral-400 mb-1">Projected Lift</p>
                                    <p className="text-3xl font-bold text-green-400 font-heading">+23% <span className="text-sm font-normal text-neutral-500 font-sans">above baseline</span></p>
                                </div>
                                <div className="pt-4 border-t border-neutral-800">
                                    <p className="text-[10px] text-neutral-500 leading-tight">
                                        Forecast based on current trajectory, seasonal mobility trends, and planned asset optimization.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
            </div>

            {/* FOOTER METHODOLOGY */}
            <div className="bg-neutral-50 border-t border-neutral-200 p-6 md:p-10 text-center">
                 <p className="text-xs font-bold text-neutral-400 uppercase tracking-widest mb-2 font-heading">Methodology & Attribution</p>
                 <p className="text-[10px] text-neutral-500 max-w-2xl mx-auto leading-relaxed">
                     Audiences modeled using mobile latency signals, POI density layers, and multi-path exposure simulation. 
                     Attribution derived using uplift modeling and channel-assisted conversions blended across search, social, 
                     retail traffic, and direct visits. Confidence score: 82%.
                 </p>
                 <p className="text-[10px] text-neutral-400 mt-6">
                     &copy; 2025 Adnoxy Intelligence Platform. Confidential Analysis.
                 </p>
            </div>
        </div>
        <div className="h-12"></div>
    </div>
  );
};

export default Report;